#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "bentopdf"
name = "BentoPDF"
description.en = "Privacy First PDF Toolkit"
description.fr = "Kit d'outils PDF Privacy First"

version = "2.7.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://bentopdf.com"
admindoc = "https://bentopdf.com/docs/self-hosting/"
code = "https://github.com/alam00000/bentopdf"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "250M"
ram.build = "0M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/alam00000/bentopdf/releases/download/v2.7.0/dist-2.7.0.zip"
    sha256 = "1d390be93be15fe9d0ea8a22bf356e5155ee72dd05be42aed3d6e7e3eb76fe17"
    format = "zip"
    extract = true
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "dist-*.zip"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"
    
    [resources.permissions]
    main.url = "/"
