#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "bentopdf"
name = "BentoPDF"
description.en = "Privacy First PDF Toolkit"
description.fr = "Kit d'outils PDF Privacy First"

version = "2.8.5~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://bentopdf.com"
admindoc = "https://bentopdf.com/docs/self-hosting/"
code = "https://github.com/alam00000/bentopdf"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "250M"
ram.build = "0M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/alam00000/bentopdf/releases/download/v2.8.5/dist-simple-2.8.5.zip"
    sha256 = "5ade3c0a661ed01e74b7d5ac9e43faa737a0c20547a68f4f1da826ef2bba3358"
    format = "zip"
    extract = true
    in_subdir = false
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "dist-simple-.*\\.zip"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
