#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REINSTALL BENTOPDF
#=================================================
ynh_script_progression "Rebuilding the app..."

pushd "$install_dir"
	if [ $new_path != "/" ]
	then
		ynh_hide_warnings ynh_exec_as_app SIMPLE_MODE=true BASE_URL=$new_path/ npm run build
	else
		ynh_hide_warnings ynh_exec_as_app SIMPLE_MODE=true npm run build
	fi
popd

chown -R $app:www-data $install_dir/dist

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
